# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv clsi-sharelatex .clsi-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .clsi-sharelatex clsi-sharelatex

EXPOSE 3013

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

