# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv chat-sharelatex .chat-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .chat-sharelatex chat-sharelatex

EXPOSE 3010

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

