# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv spelling-sharelatex .spelling-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .spelling-sharelatex spelling-sharelatex

EXPOSE 3005

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

