# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv docstore-sharelatex .docstore-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .docstore-sharelatex docstore-sharelatex

EXPOSE 3016

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

