# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv real-time-sharelatex .real-time-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .real-time-sharelatex real-time-sharelatex

EXPOSE 3026

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

