# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv document-updater-sharelatex .document-updater-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .document-updater-sharelatex document-updater-sharelatex

EXPOSE 3003

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

