# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv filestore-sharelatex .filestore-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .filestore-sharelatex filestore-sharelatex

EXPOSE 3009

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

