version: '2.2'
services:
    sharelatex:
        restart: always
        image: zevin/sharelatex
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
            clsi:
                condition: service_started
            filestore:
                condition: service_started
            docstore:
                condition: service_started
            chat:
                condition: service_started
            spelling:
                condition: service_started
        privileged: true
        ports:
            - 80:80
        links:
            - mongo
            - redis
            - clsi
            - chat
            - docstore
            - filestore
            - spelling
        volumes:
            - ~/vol/sharelatex_data:/var/lib/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # SHARELATEX_SITE_URL: http://sharelatex.mydomain.com
            # SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
            # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            # SHARELATEX_ADMIN_EMAIL: support@it.com

            # SHARELATEX_PROXY_LEARN: "true"

    clsi:
        restart: always
        image: zevin/clsi
        container_name: clsi
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3013:3013
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/clsi_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            SPELLING_HOST: spelling
            DOCSTORE_HOST: docstore
            LISTEN_ADDRESS: clsi
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'

    filestore:
        restart: always
        image: zevin/filestore
        container_name: filestore
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
          clsi:
                condition: service_started
        privileged: true
        ports:
            - 3009:3009
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/filestore_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            LISTEN_ADDRESS: filestore
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'

    docstore:
        restart: always
        image: zevin/docstore
        container_name: docstore
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3016:3016
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/docstore_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            SPELLING_HOST: spelling
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            LISTEN_ADDRESS: docstore
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'

    chat:
        restart: always
        image: zevin/chat
        container_name: chat
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3010:3010
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/chat_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            SPELLING_HOST: spelling
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            WEB_HOST: sharelatex
            LISTEN_ADDRESS: chat
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'

    spelling:
        restart: always
        image: zevin/spelling
        container_name: spelling
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3005:3005
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/spelling_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            WEB_HOST: sharelatex
            LISTEN_ADDRESS: spelling
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'



    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - ~/vol/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/vol/redis_data:/data
    
    