version: '2.2'
services:
    sharelatex:
        restart: always
        image: zevin/sharelatex
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
            clsi:
                condition: service_started
            filestore:
                condition: service_started
            docstore:
                condition: service_started
            chat:
                condition: service_started
            spelling:
                condition: service_started
            tags:
                condition: service_started
            notifications:
                condition: service_started
            contacts:
                condition: service_started
            document_updater:
                condition: service_started
            web:
                condition: service_started
            real_time:
                condition: service_started
            trackchanges:
                condition: service_started
        privileged: true
        ports:
            - 80:80
        links:
            - mongo
            - redis
            - clsi
            - chat
            - docstore
            - filestore
            - spelling
            - tags
            - notifications
            - contacts
            - document_updater
            - web
            - real_time
            - trackchanges
        volumes:
            - ~/vol/sharelatex_data:/var/lib/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            WEB_HOST: web
            TAGS_HOST: tags
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            FILESTORE_HOST: filestore
            DOCUMENT_UPDATER_HOST: document_updater
            CONTACTS_HOST: contacts
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            REALTIME_HOST: real_time
            TRACK_CHANGES_HOST: trackchanges

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # SHARELATEX_SITE_URL: http://sharelatex.mydomain.com
            # SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
            # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            # SHARELATEX_ADMIN_EMAIL: support@it.com

            # SHARELATEX_PROXY_LEARN: "true"

    clsi:
        restart: always
        image: zevin/clsi
        container_name: clsi
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3013:3013
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/clsi_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            TAGS_HOST: tags
            CHAT_HOST: chat
            SPELLING_HOST: spelling
            NOTIFICATIONS_HOST: notifications
            WEB_HOST: web
            DOCSTORE_HOST: docstore
            LISTEN_ADDRESS: clsi
            DOCUMENT_UPDATER_HOST: document_updater
            CONTACTS_HOST: contacts
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            TRACK_CHANGES_HOST: trackchanges
            ENABLE_CONVERSIONS: 'true'

    filestore:
        restart: always
        image: zevin/filestore
        container_name: filestore
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
          clsi:
                condition: service_started
        privileged: true
        ports:
            - 3009:3009
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/filestore_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            TAGS_HOST: tags
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            LISTEN_ADDRESS: filestore
            NOTIFICATIONS_HOST: notifications
            CONTACTS_HOST: contacts
            WEB_HOST: web
            FILESTORE_HOST: filestore
            DOCUMENT_UPDATER_HOST: document_updater
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            TRACK_CHANGES_HOST: trackchanges

    docstore:
        restart: always
        image: zevin/docstore
        container_name: docstore
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3016:3016
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/docstore_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            SPELLING_HOST: spelling
            TAGS_HOST: tags
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            LISTEN_ADDRESS: docstore
            NOTIFICATIONS_HOST: notifications
            WEB_HOST: web
            DOCUMENT_UPDATER_HOST: document_updater
            CONTACTS_HOST: contacts
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            TRACK_CHANGES_HOST: trackchanges

    chat:
        restart: always
        image: zevin/chat
        container_name: chat
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3010:3010
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/chat_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            SPELLING_HOST: spelling
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            TAGS_HOST: tags
            NOTIFICATIONS_HOST: notifications
            WEB_HOST: web
            LISTEN_ADDRESS: chat
            DOCUMENT_UPDATER_HOST: document_updater
            CONTACTS_HOST: contacts
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            TRACK_CHANGES_HOST: trackchanges
            ENABLE_CONVERSIONS: 'true'

    spelling:
        restart: always
        image: zevin/spelling
        container_name: spelling
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3005:3005
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/spelling_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            TAGS_HOST: tags
            WEB_HOST: web
            NOTIFICATIONS_HOST: notifications
            LISTEN_ADDRESS: spelling
            DOCUMENT_UPDATER_HOST: document_updater
            CONTACTS_HOST: contacts
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            TRACK_CHANGES_HOST: trackchanges


    notifications:
        restart: always
        image: zevin/notifications
        container_name: notifications
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3042:3042
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/notifications_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            WEB_HOST: web
            LISTEN_ADDRESS: notifications
            TAGS_HOST: tags
            NOTIFICATIONS_HOST: notifications
            DOCUMENT_UPDATER_HOST: document_updater
            CONTACTS_HOST: contacts
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            TRACK_CHANGES_HOST: trackchanges
            ENABLE_CONVERSIONS: 'true'

    tags:
        restart: always
        image: zevin/tags
        container_name: tags
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3012:3012
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/tags_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            DOCUMENT_UPDATER_HOST: document_updater
            WEB_HOST: web
            NOTIFICATIONS_HOST: notifications
            LISTEN_ADDRESS: tags
            CONTACTS_HOST: contacts
            TAGS_HOST: tags
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            TRACK_CHANGES_HOST: trackchanges

           
    contacts:
        restart: always
        image: zevin/contacts
        container_name: contacts
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3036:3036
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/contacts_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            WEB_HOST: web
            NOTIFICATIONS_HOST: notifications
            LISTEN_ADDRESS: contacts
            CONTACTS_HOST: contacts
            TAGS_HOST: tags
            DOCUMENT_UPDATER_HOST: document_updater
            FILESTORE_HOST: filestore
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            TRACK_CHANGES_HOST: trackchanges
 

    document_updater:
        restart: always
        image: zevin/document_updater
        container_name: document_updater
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3003:3003
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/document_updater_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            WEB_HOST: web
            NOTIFICATIONS_HOST: notifications
            LISTEN_ADDRESS: document_updater
            CONTACTS_HOST: contacts
            TAGS_HOST: tags
            FILESTORE_HOST: filestore
            DOCUMENT_UPDATER_HOST: document_updater
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            TRACK_CHANGES_HOST: trackchanges

    web:
        restart: always
        image: zevin/web
        container_name: web
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3000:3000
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/web_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            WEB_HOST: web
            NOTIFICATIONS_HOST: notifications
            LISTEN_ADDRESS: web
            CONTACTS_HOST: contacts
            TAGS_HOST: tags
            FILESTORE_HOST: filestore
            DOCUMENT_UPDATER_HOST: document_updater
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            REALTIME_HOST: real_time
            TRACK_CHANGES_HOST: trackchanges
            

    real_time:
        restart: always
        image: zevin/real_time
        container_name: real_time
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3026:3026
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/real_time_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            WEB_HOST: web
            NOTIFICATIONS_HOST: notifications
            LISTEN_ADDRESS: real_time
            CONTACTS_HOST: contacts
            TAGS_HOST: tags
            FILESTORE_HOST: filestore
            DOCUMENT_UPDATER_HOST: document_updater
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            REALTIME_HOST: real_time
            TRACK_CHANGES_HOST: trackchanges
            

    trackchanges:
        restart: always
        image: zevin/trackchanges
        container_name: trackchanges
        depends_on:
          mongo:
              condition: service_healthy
          redis:
              condition: service_started
        privileged: true
        ports:
            - 3015:3015
        links:
            - mongo
            - redis
        volumes:
            - ~/vol/trackchanges_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
          
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
          
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            CLSI_HOST: clsi
            CHAT_HOST: chat
            DOCSTORE_HOST: docstore
            SPELLING_HOST: spelling
            WEB_HOST: web
            NOTIFICATIONS_HOST: notifications
            LISTEN_ADDRESS: trackchanges
            CONTACTS_HOST: contacts
            TAGS_HOST: tags
            FILESTORE_HOST: filestore
            DOCUMENT_UPDATER_HOST: document_updater
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            REALTIME_HOST: real_time
            TRACK_CHANGES_HOST: trackchanges


    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - ~/vol/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/vol/redis_data:/data
    
    