# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv tags-sharelatex .tags-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .tags-sharelatex tags-sharelatex

EXPOSE 3012

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

