# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv contacts-sharelatex .contacts-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .contacts-sharelatex contacts-sharelatex

EXPOSE 3036

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

