# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv track-changes-sharelatex .track-changes-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .track-changes-sharelatex track-changes-sharelatex
COPY ${baseDir}/settings.coffee /etc/sharelatex/settings.coffee
