# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv web-sharelatex .web-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .web-sharelatex web-sharelatex

EXPOSE 3000

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

