# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv notifications-sharelatex .notifications-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .notifications-sharelatex notifications-sharelatex

EXPOSE 3042

WORKDIR /

ENTRYPOINT ["/sbin/my_init"]

