# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# zevin version
# ---------------------------------------------

FROM sharelatex/sharelatex:2.2.0

ENV baseDir .

RUN cd /etc/service && mv web-sharelatex .web-sharelatex  && rm -rf *-sharelatex && rm -rf nginx && mv .web-sharelatex web-sharelatex

COPY ${baseDir}/settings.coffee /etc/sharelatex/settings.coffee
